#!/usr/bin/env python
import os
import subprocess
import ROOT
ROOT.gROOT.SetBatch()

showlabel = False

for dirpath, dirnames, filenames in os.walk('.'):
    for filename in filenames:
        name, ext = os.path.splitext(filename)
        if ext != '.py':
            continue
        if 'rootpy' in name:
            listingname = 'rootpy'
        else:
            listingname = 'PyROOT'
        content = open(filename, 'r').readlines()
        with open(os.path.join(dirpath, name + '.tex'), 'w') as f:
            f.write('\\begin{footnotesize}\n')
            if showlabel:
                caption = content[0].strip('# ')
                f.write('\\begin{pyglist}[language=python,texcl=true,abovecaptionskip=0,style=vs,bgcolor=Moccasin,caption={%s},listingname=\\textbf{%s}]\n'
                        % (caption, listingname))
            else:
                f.write('\\begin{pyglist}[language=python,texcl=true,abovecaptionskip=0,style=vs,bgcolor=Moccasin]\n')
            f.writelines(content[1:])
            f.write('\\end{pyglist}\n')
            f.write('\\end{footnotesize}\n')
        # run the script and write the output
        proc = subprocess.Popen(['python', filename],
                stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
        output = proc.communicate()[0]
        with open(os.path.join(dirpath, name + '_output.tex'), 'w') as f:
            f.write('\\begin{footnotesize}\n')
            f.write('\\begin{pyglist}[language=text,texcl=true,abovecaptionskip=0,style=bw]\n')
            f.write(output)
            f.write('\\end{pyglist}\n')
            f.write('\\end{footnotesize}\n')
