#!/usr/bin/env python
import os

for dirpath, dirnames, filenames in os.walk('.'):
    for filename in filenames:
        name, ext = os.path.splitext(filename)
        if ext != '.py':
            continue
        content = open(filename, 'r').readlines()
        with open(os.path.join(dirpath, name + '.tex'), 'w') as f:
            f.write('\\begin{footnotesize}\n')
            f.write('\\begin{pyglist}[language=python,texcl=true,style=vs,bgcolor=Moccasin]\n')
            f.writelines(content)
            f.write('\\end{pyglist}\n')
            f.write('\\end{footnotesize}\n')
